module.exports = {
  beginnings: [
    "The company",
    "The team",
    "The management",
    "The employee-base",
    "The majority of the decision makers",
  ],
  helperVerbs: [
    "should",
    "needs to",
    "must",
    "has to",
  ],
  adverbs: [
    "appropriately",
    "assertively",
    "authoritatively",
    "collaboratively",
    "compellingly",
    "competently",
    "completely",
    "continually",
    "conveniently",
    "credibly",
    "distinctively",
    "dramatically",
    "dynamically",
    "efficiently",
    "energistically",
    "enthusiastically",
    "fungibly",
    "globally",
    "holisticly",
    "interactively",
    "intrinsically",
    "monotonectally",
    "objectively",
    "phosfluorescently",
    "proactively",
    "professionally",
    "progressively",
    "quickly",
    "rapidiously",
    "seamlessly",
    "synergistically",
    "uniquely",
  ],
  verbs: [
    "actualise",
    "administrate",
    "aggregate",
    "analyse",
    "architect",
    "benchmark",
    "brand",
    "build",
    "cloudify",
    "communicate",
    "conceptualise",
    "coordinate",
    "create",
    "cultivate",
    "customise",
    "deliver",
    "deploy",
    "develop",
    "disseminate",
    "drive",
    "embrace",
    "empower",
    "enable",
    "engage",
    "engineer",
    "enhance",
    "envisioneer",
    "evisculate",
    "evolve",
    "expedite",
    "exploit",
    "extend",
    "fabricate",
    "facilitate",
    "fashion",
    "formulate",
    "foster",
    "generate",
    "green-field",
    "grow",
    "harness",
    "impact",
    "implement",
    "incentivise",
    "incubate",
    "initiate",
    "innovate",
    "integrate",
    "iterate",
    "leverage existing",
    "maintain",
    "matrix",
    "maximise",
    "mesh",
    "monetise",
    "monetise",
    "morph",
    "myocardinate",
    "negotiate",
    "network",
    "optimise",
    "orchestrate",
    "parallel task",
    "park",
    "plagiarise",
    "play hardball",
    "pontificate",
    "predominate",
    "procrastinate",
    "productivate",
    "productise",
    "promote",
    "provide access to",
    "pursue",
    "re-enable",
    "re-engineer",
    "recaptiualise",
    "reconceptualise",
    "redefine",
    "reintermediate",
    "reinvent",
    "repurpose",
    "restore",
    "revolutionise",
    "right-shore",
    "right-size",
    "scale",
    "seize",
    "simplify",
    "step up",
    "strategise",
    "streamline",
    "supply",
    "syndicate",
    "synergise",
    "synthesise",
    "take a step back",
    "target",
    "touch base",
    "transform",
    "transformatise",
    "transition",
    "underwhelm",
    "unleash",
    "upscale",
    "utilise",
    "visualise",
    "whiteboard",
  ],
  prepositions: [
    "with",
    "about",
    "for",
    "the",
  ],
  nouns: [
    "action items",
    "alignments",
    "applications",
    "architectures",
    "ballpark figures",
    "bandwidth",
    "benchmarking",
    "benefits",
    "best practices",
    "blue ocean",
    "brainstorm",
    "cash cow",
    "catalysts for change",
    "channels",
    "clouds",
    "collaboration and idea-sharing",
    "communities",
    "content",
    "convergence",
    "core competencies",
    "customer incentives",
    "customer satisfaction",
    "customer service",
    "data",
    "data-driven",
    "dealbreakers",
    "deliverables",
    "double-sided marketplace",
    "e-business",
    "e-commerce",
    "e-markets",
    "e-services",
    "e-tailers",
    "elevator pitches",
    "experiences",
    "expertise",
    "five forces analysis",
    "functionalities",
    "fungibility",
    "game changers",
    "growth strategies",
    "human capital",
    "ideas",
    "imperatives",
    "industry standards",
    "infomediaries",
    "information",
    "infrastructures",
    "initiatives",
    "innovation",
    "intellectual capital",
    "interfaces",
    "leadership skills",
    "leadership",
    "low-handing fruit",
    "manufactured products",
    "markets",
    "materials",
    "meta-services",
    "methodologies",
    "methods of empowerment",
    "metrics",
    "mindshare",
    "models",
    "multitasking",
    "networks",
    "next-generation solution",
    "niche markets",
    "niches",
    "open-door policy",
    "opportunities",
    "organic sources",
    "outside the box thinking",
    "outsourcing",
    "paradigm shift",
    "paradigms",
    "partnerships",
    "platforms",
    "portals",
    "potentialities",
    "processes",
    "products",
    "quality vectors",
    "quick wins",
    "relationships",
    "reorganisation",
    "resources",
    "restructuralisation",
    "results",
    "process improvements",
    "ROI",
    "rubber meets the road",
    "scenarios",
    "schemas",
    "seamless integration",
    "services",
    "solutions",
    "sources",
    "storage",
    "strategic theme areas",
    "supply chains",
    "SWOT analysis",
    "synergies",
    "synergy",
    "systems",
    "team players",
    "team players",
    "technologies",
    "technology",
    "testing procedures",
    "the 80-20 rule",
    "the bottom line",
    "total linkage",
    "users",
    "value",
    "virtualization",
    "visionaries",
    "vortals",
    "web 2.0",
    "web services",
    "web-readiness",
    "whiteboard",
    "win-win situation",
  ],
  endings: [
    "in the long run",
    "this quarter",
    "to drive profitability",
    "to ensure scalability",
    "to scale the offline aspect",
    "to become the Nike of the industry",
    "to move up the value chain",
    "to stay on the bleeding edge",
  ],
}